# Файл конфигурации для Netlify
[build]
  command = "npm run build"
  publish = "dist"
  
# Настройка перенаправлений для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Заголовки для безопасности и кэширования
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
# Заголовки для кэширования статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"